version: '3'

services:
  front:
    container_name: pyccel-front
    build:
      context: ./frontend/.
      dockerfile: ../compose/front/Dockerfile
      # network: host
    volumes:
      - ./frontend:/opt/app
      - /opt/app/node_modules
      - /opt/app/.next
    ports:
      - '3000:3000'
    networks:
      - PyccelNetwork
  backend:
    container_name: pyccel-backend
    build:
      context: ./backend/
      dockerfile: ./backend/Dockerfile
    ports:
      - '8000:8000'
    networks:
      - PyccelNetwork
    restart: always

networks:
  PyccelNetwork:
    driver: bridge
